### ISSUE TITLE
crash on caging

### ISSUE THREAD

**Issue by Cronosus** [Quintinity/MobCages#8]
<code>
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at quintinity.mods.mobcages.client.RenderCage.getEntity(RenderCage.java:107)
    at quintinity.mods.mobcages.client.MobCageItemRenderer.renderItem(MobCageItemRenderer.java:46)
    at net.minecraftforge.client.ForgeHooksClient.renderEquippedItem(ForgeHooksClient.java:220)
    at net.minecraft.client.renderer.ItemRenderer.renderItem(ItemRenderer.java:80)
    at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:499)
    at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:736)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1361)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:282)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:364)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at quintinity.mods.mobcages.client.RenderCage.getEntity(RenderCage.java:107)
    at quintinity.mods.mobcages.client.MobCageItemRenderer.renderItem(MobCageItemRenderer.java:46)
    at net.minecraftforge.client.ForgeHooksClient.renderEquippedItem(ForgeHooksClient.java:220)
    at net.minecraft.client.renderer.ItemRenderer.renderItem(ItemRenderer.java:80)
    at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:499)
    at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:736)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1361)
</code>

**Comment by vladmarica** [comment]
What mob were you trying to cage?

**Comment by Cronosus** [comment]
sheep
chicken
pig
i tested it and when i clicked to them, game crashed.

**Comment by Cronosus** [comment]
i test it again, and found it
when i just place empty cage on ground, then it crashes

**Comment by vladmarica** [comment]
I cannot replicate your crash. I need a list of all the mods you have installed.

**Comment by Cronosus** [comment]
i tried separately with every mod in my modpack and found it.
its caused by Wawla (addon for Waila)
http://minecraft.curseforge.com/projects/wawla-what-are-we-looking-at

**Comment by Cronosus** [comment]
ok, working
thanks
